src/todo/urls.py
from django.urls import path
from .views import HomeView, SignUp, complete, DeleteTodo, UpdateTodo

app_name = "todo"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('signup', SignUp.as_view(), name='signup'),
    path('complete/<int:pk>', complete, name='complete'),
    path('delete/<int:pk>', DeleteTodo.as_view(), name='delete'),
    path('update/<int:pk>', UpdateTodo.as_view(), name='update'),
]

src/todoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('todo.urls',  namespace='todo')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/todo/models.py
from django.db import models
from django.contrib.auth import get_user_model
from datetime import datetime

from django.urls import reverse

User = get_user_model()

class TodoApp(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    todo = models.CharField(max_length=500)
    created_date = models.DateTimeField(default=datetime.now)
    is_complete = models.BooleanField(default=False)
    due_date = models.DateTimeField(default=datetime.now)
    
    def __str__(self):
        return self.user.username
    
    def get_absolute_url(self):
        return reverse('todo:home')

src/todo/forms.py
from django import forms
from .models import TodoApp
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoApp
        fields = ['todo']

        widgets = {
            'todo': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Add a todo'})
        }
        

class UpdateTodoForm(forms.ModelForm):
    class Meta:
        model = TodoApp
        fields = ['todo']

        widgets = {
            'todo': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Add a todo'})
        }

        
class SignUpForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        

src/todo/views.py
from django.shortcuts import redirect
from django.http import HttpResponse
from django.views.generic import CreateView, DeleteView, UpdateView
from .models import TodoApp
from .forms import TodoForm, SignUpForm, UpdateTodoForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class HomeView(LoginRequiredMixin, CreateView):
    login_url = 'login'
    model = TodoApp
    form_class = TodoForm
    template_name = 'index.html'
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_context_data(self, *args, **kwargs):
        context = super(HomeView, self).get_context_data(*args, **kwargs)
    
        todos = TodoApp.objects.filter(user=self.request.user)
        context['todos'] = todos
        
        
        
        return context

    
def complete(request, pk=None):
    todoApp = TodoApp.objects.get(id=pk)
    if todoApp.is_complete == True:
        todoApp.is_complete = False
    else:
        todoApp.is_complete = True
    todoApp.save()
    return redirect('todo:home')     
    

class DeleteTodo(LoginRequiredMixin, DeleteView):
    login_url = 'login'
    model = TodoApp
    template_name = 'delete.html'
    
    success_url = reverse_lazy('todo:home')
   

class UpdateTodo(LoginRequiredMixin, UpdateView):
    login_url = 'login'
    model = TodoApp
    form_class = UpdateTodoForm
    template_name = 'update.html'
    
    success_url = reverse_lazy('todo:home')
    
    
    
 
class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'registration/signup.html'
    
    success_url = reverse_lazy('login')

src/todo/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
        {% block title %}
            Home
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    
    <link rel="stylesheet" href="https://mdbcdn.b-cdn.net/wp-content/themes/mdbootstrap4/docs-app/css/dist/mdb5/standard/core.min.css">
    <link rel="stylesheet" id="roboto-subset.css-css" href="https://mdbcdn.b-cdn.net/wp-content/themes/mdbootstrap4/docs-app/css/mdb5/fonts/roboto-subset.css?ver=3.9.0-update.5" type="text/css" media="all">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" defer></script>
</head>
<body>

    {% block content %}

    {% endblock %}

</body>
</html>

src/todo/templates/delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Sign In 
{% endblock %}

{% block content %}
    <section class="vh-100">
    
        <div class="container py-5 h-100">
          
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">
              
              <div class="card" id="list1" style="border-radius: .75rem; background-color: #eff1f2;">
                <h2 class="name m-4 px-0">Welcome {{ user.username }} <a href="{% url 'logout' %}"><button type="button" class="btn btn-primary">Logout</button></a></h2>
            
                <div class="card-body py-4 px-4 px-md-5">
      
                  <p class="h1 text-center mt-3 mb-4 pb-3 text-primary">
                    <i class="fas fa-check-square me-1"></i>
                    <u>Delete Todo</u>
                  </p>
      
                  <div class="pb-2">
                    <div class="card">
                      <div class="card-body">
                        <form action="" method="POST">
                          {% csrf_token %}
                          
                          <div class="d-flex flex-row align-items-center">
                            
                            <h1> Are you sure you want to delete this todo</h1>
                            <div>
                              <button type="submit" class="btn btn-primary">Delete</button>
                          
                            </div>
                        </form>
                        </div>
                      </div>
                    </div>
                  </div>

                  <hr class="my-4">    
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

{% endblock%}

src/todo/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="vh-100">
    
        <div class="container py-5 h-100">
          
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">
              
              <div class="card" id="list1" style="border-radius: .75rem; background-color: #eff1f2;">
                <h2 class="name m-4 px-0">Welcome {{ user.username }} <a href="{% url 'logout' %}"><button type="button" class="btn btn-primary">Logout</button></a></h2>
        
                <div class="card-body py-4 px-4 px-md-5">
      
                  <p class="h1 text-center mt-3 mb-4 pb-3 text-primary">
                    <i class="fas fa-check-square me-1"></i>
                    <u>My Todo-s</u>
                  </p>
      
                  <div class="pb-2">
                    <div class="card">
                      <div class="card-body">
                        <form action="" method="POST">
                          {% csrf_token %}
                          
                          <div class="d-flex flex-row align-items-center">
                            {{ form }}
                            {% comment %} <input type="text" class="form-control form-control-lg" id="exampleFormControlInput1"
                              placeholder="Add new..."> {% endcomment %}
      
                            
                            <div>
                              <button type="submit" class="btn btn-primary">Add</button>
                          
                            </div>
                        </form>
                        </div>
                      </div>
                    </div>
                  </div>

                  <hr class="my-4">
      
                  <!-- <div class="d-flex justify-content-end align-items-center mb-4 pt-2 pb-3">
                    <p class="small mb-0 me-2 text-muted">Filter</p>
                    <select class="select">
                      <option value="1">All</option>
                      <option value="2">Completed</option>
                      <option value="3">Active</option>
                    </select>
                   
                  </div> -->

                  {% for todo in todos %}
                  <ul class="list-group list-group-horizontal rounded-0 bg-transparent">
                    <li
                      class="list-group-item d-flex align-items-center ps-0 pe-3 py-1 rounded-0 border-0 bg-transparent">
              
                        <a href="{% url 'todo:complete' todo.pk %}" style="display: block; width: 100%; z-index: 10 ">
                          <div class="form-check">
                            {% if todo.is_complete %}
                              <input class="form-check-input me-0" name="checkbox" type="checkbox" value="clicked" id="flexCheckChecked1"
                              aria-label="..." checked />
                            {% else %}
                              <input class="form-check-input me-0" name="check" type="checkbox" value="clicked" id="flexCheckChecked1"
                              aria-label="..." />
                            {% endif %}
                          </div>
                        </a>
                    
                    </li>
                    <li
                      class="list-group-item px-3 py-1 d-flex align-items-center flex-grow-1 border-0 bg-transparent">
                      <p class="lead fw-normal mb-0">{{todo.todo}}</p>
                    </li>
                    <li class="list-group-item ps-3 pe-0 py-1 rounded-0 border-0 bg-transparent">
                      <div class="d-flex flex-row justify-content-end mb-1">
                        <a href="{% url 'todo:update' todo.pk %}" class="text-info" data-mdb-toggle="tooltip" title="Edit todo"><i
                            class="fas fa-pencil-alt me-3"></i></a>
                        <a href="{% url 'todo:delete' todo.pk %}" class="text-danger" data-mdb-toggle="tooltip" title="Delete todo"><i
                            class="fas fa-trash-alt"></i></a>
                      </div>
                      <div class="text-end text-muted">
                        <a href="#!" class="text-muted" data-mdb-toggle="tooltip" title="Created date">
                          <p class="small mb-0"><i class="fas fa-info-circle me-2"></i>{{ todo.created_date.date }}</p>
                        </a>
                      </div>
                    </li>
                  </ul>
                  {% endfor %}
      
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

{% endblock%}

src/todo/templates/update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Sign In 
{% endblock %}

{% block content %}
    <section class="vh-100">
    
        <div class="container py-5 h-100">
          
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">
              
              <div class="card" id="list1" style="border-radius: .75rem; background-color: #eff1f2;">
                <h2 class="name m-4 px-0">Welcome {{ user.username }} <a href="{% url 'signout' %}"><button type="button" class="btn btn-primary">Logout</button></a></h2>
            
                <div class="card-body py-4 px-4 px-md-5">
      
                  <p class="h1 text-center mt-3 mb-4 pb-3 text-primary">
                    <i class="fas fa-check-square me-1"></i>
                    <u>Update Todo</u>
                  </p>
      
                  <div class="pb-2">
                    <div class="card">
                      <div class="card-body">
                        <form action="" method="POST">
                          {% csrf_token %}
                          
                          <div class="d-flex flex-row align-items-center">
                            {{ form}}
                            
                            <div>
                              <button type="submit" class="btn btn-primary">Update</button>
                          
                            </div>
                        </form>
                        </div>
                      </div>
                    </div>
                  </div>

                  <hr class="my-4">    
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

{% endblock%}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="vh-100">
    
        <div class="container py-5 h-100">
          
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">
              
              <div class="card" id="list1" style="border-radius: .75rem; background-color: #eff1f2;">
                <h2 class="name m-4 px-0">Welcome {{ user.username }} <a href="signout"><button type="button" class="btn btn-primary">Logout</button></a></h2>
        
                <div class="card-body py-4 px-4 px-md-5">
      
                  <p class="h1 text-center mt-3 mb-4 pb-3 text-primary">
                    <i class="fas fa-check-square me-1"></i>
                    <u>My Todo-s</u>
                  </p>
      
                  <div class="pb-2">
                    <div class="card">
                      <div class="card-body">
                        <form action="" method="POST">
                          {% csrf_token %}
                          
                          <div class="d-flex flex-row align-items-center">
                            {{ form_class}}
                            {% comment %} <input type="text" class="form-control form-control-lg" id="exampleFormControlInput1"
                              placeholder="Add new..."> {% endcomment %}
      
                            
                            <div>
                              <button type="submit" class="btn btn-primary">Add</button>
                          
                            </div>
                        </form>
                        </div>
                      </div>
                    </div>
                  </div>

                  <hr class="my-4">
      
                  <div class="d-flex justify-content-end align-items-center mb-4 pt-2 pb-3">
                    <p class="small mb-0 me-2 text-muted">Filter</p>
                    <select class="select">
                      <option value="1">All</option>
                      <option value="2">Completed</option>
                      <option value="3">Active</option>
                    </select>
                   
                  </div>

                  {% for todo in todos %}
                  <ul class="list-group list-group-horizontal rounded-0 bg-transparent">
                    <li
                      class="list-group-item d-flex align-items-center ps-0 pe-3 py-1 rounded-0 border-0 bg-transparent">
                      <a href="{% url 'complete' todo.pk %}" style="display: block; width: 100%; z-index: 10 ">
                        <div class="form-check">
                          {% if todo.is_complete %}
                            <input class="form-check-input me-0" type="checkbox" value="" id="flexCheckChecked1"
                            aria-label="..." checked />
                          {% else %}
                            <input class="form-check-input me-0" type="checkbox" value="" id="flexCheckChecked1"
                            aria-label="..." />
                          {% endif %}
                        </div>
                      </a>
                    </li>
                    <li
                      class="list-group-item px-3 py-1 d-flex align-items-center flex-grow-1 border-0 bg-transparent">
                      <p class="lead fw-normal mb-0">{{todo.todo}}</p>
                    </li>
                    <li class="list-group-item ps-3 pe-0 py-1 rounded-0 border-0 bg-transparent">
                      <div class="d-flex flex-row justify-content-end mb-1">
                        <a href="{% url 'update' todo.pk %}" class="text-info" data-mdb-toggle="tooltip" title="Edit todo"><i
                            class="fas fa-pencil-alt me-3"></i></a>
                        <a href="{% url 'delete' todo.pk %}" class="text-danger" data-mdb-toggle="tooltip" title="Delete todo"><i
                            class="fas fa-trash-alt"></i></a>
                      </div>
                      <div class="text-end text-muted">
                        <a href="#!" class="text-muted" data-mdb-toggle="tooltip" title="Created date">
                          <p class="small mb-0"><i class="fas fa-info-circle me-2"></i>{{ todo.created_date.date }}</p>
                        </a>
                      </div>
                    </li>
                  </ul>
                  {% endfor %}
      
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

{% endblock%}

templates/signin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Sign In 
{% endblock %}

{% block content %}


    <section class="vh-100" >
        <div class="container-fluid h-custom " style="min-height:100vh; display: flex; flex-direction: column; justify-content: center">
          <h1 class="text-center mb-4">Welcome to Todo App</h1>
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
              <h5 style="color: red;"> 
                {% for msg in messages %}
                  {{ msg }}
                {% endfor %}
              </h5>
              <form action="" method="POST">
                {% csrf_token %}
                <h1 class="mb-4 text-center">Login </h1>
                
                <!-- Email input -->
                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example3">Username</label>
                  <input type="text" name="username" id="form3Example3" class="form-control form-control-lg"
                    placeholder="Username" />
                  
                </div>
      
                <!-- Password input -->
                <div class="form-outline mb-3">
                  <label class="form-label" for="form3Example4">Password</label>
                  <input type="password" name="password" id="form3Example4" class="form-control form-control-lg"
                    placeholder="Enter password" />
                  
                </div>
      
            
      
                <div class="text-center text-lg-start mt-4 pt-2">
                  <button type="submit" class="btn btn-primary btn-lg"
                    style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
                  <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="/signup"
                      class="link-danger">Register</a></p>
                </div>
      
              </form>
            </div>
          </div>
        </div>
        <div
          class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
          <!-- Copyright -->
          <div class="text-white mb-3 mb-md-0">
            Copyright © 2020. All rights reserved.
          </div>
          <!-- Copyright -->
      
          <!-- Right -->
          <div>
            <a href="#!" class="text-white me-4">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a href="#!" class="text-white me-4">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="#!" class="text-white me-4">
              <i class="fab fa-google"></i>
            </a>
            <a href="#!" class="text-white">
              <i class="fab fa-linkedin-in"></i>
            </a>
          </div>
          <!-- Right -->
        </div>
      </section>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Sign Up 
{% endblock %}

{% block content %}



<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <h1 class="text-center" >Welcome to Todo App</h1>
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
                  <h5 style="color: red;"> 
                    {% for msg in messages %}
                      {{ msg }}
                    {% endfor %}
                  </h5>
                  <form class="mx-1 mx-md-4" action="" method="POST">
                    {% csrf_token %}
                   
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <label class="form-label" for="form3Example1c">Username</label>
                        <input type="text" name="username" id="form3Example1c" class="form-control" />
                        
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <label class="form-label" for="form3Example3c">Your Email</label>
                        <input type="email" name="email" id="form3Example3c" class="form-control" />
                        
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <label class="form-label" for="form3Example4c">Password</label>
                        <input type="password" name="password" id="form3Example4c" class="form-control" />
                        
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <label class="form-label" for="form3Example4cd">Repeat your password</label>
                        <input type="password" name="password2" id="form3Example4cd" class="form-control" />
                       
                      </div>
                    </div>

  
                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <button type="submit" class="btn btn-primary btn-lg mr-5">Register</button>
                      <p class="small fw-bold mt-2 pt-1 mb-0 ">Already have an account? <a href="/signin"
                        class="link-danger">Login</a></p>
                    </div>
  
                  </form>
  
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
  
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}